<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DetaiSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('detai')->insert([
            [
                'MaSo' => 1,
                'TenDeTai' => 'AI trong phân tích dữ liệu',
                'ChuNhiem' => 'Nguyễn Văn An',
                'DonVi' => 'CNTT',
                'CapDeTai' => 'Cấp trường',
                'LoaiDeTai' => 'Nghiên cứu',
                'ThoiGianBatDau' => '2024-01-01',
                'ThoiGianKetThuc' => '2024-12-01',
                'TrangThai' => 'đang thực hiện',
                'MucTieu' => 'Ứng dụng AI',
                'NoiDungChinh' => 'Machine learning',
                'ThanhVien' => 'An,Bình',
                'KetQua' => 'Đang thử nghiệm',
                'FileSanPham' => 'sp1.pdf',
                'KinhPhi' => 20000000,
            ],
            [
                'MaSo' => 2,
                'TenDeTai' => 'Blockchain trong giáo dục',
                'ChuNhiem' => 'Trần Minh Hùng',
                'DonVi' => 'CNTT',
                'CapDeTai' => 'Cấp bộ',
                'LoaiDeTai' => 'Nghiên cứu',
                'ThoiGianBatDau' => '2023-01-01',
                'ThoiGianKetThuc' => '2024-01-01',
                'TrangThai' => 'hoàn thành',
                'MucTieu' => 'Blockchain',
                'NoiDungChinh' => 'Xây dựng hệ thống',
                'ThanhVien' => 'Hùng,Phúc',
                'KetQua' => 'Hoàn thành',
                'FileSanPham' => 'sp2.pdf',
                'KinhPhi' => 30000000,
            ],
            [
                'MaSo' => 3,
                'TenDeTai' => 'Phân tích dữ liệu lớn',
                'ChuNhiem' => 'Lê Thu Hà',
                'DonVi' => 'HTTT',
                'CapDeTai' => 'Cấp trường',
                'LoaiDeTai' => 'Nghiên cứu',
                'ThoiGianBatDau' => '2024-03-01',
                'ThoiGianKetThuc' => '2025-03-01',
                'TrangThai' => 'đang thực hiện',
                'MucTieu' => 'BigData',
                'NoiDungChinh' => 'Hadoop Spark',
                'ThanhVien' => 'Hà,Nam',
                'KetQua' => 'Đang làm',
                'FileSanPham' => 'sp3.pdf',
                'KinhPhi' => 25000000,
            ],
            [
                'MaSo' => 4,
                'TenDeTai' => 'IoT trong nông nghiệp',
                'ChuNhiem' => 'Phạm Quang Dũng',
                'DonVi' => 'CNTT',
                'CapDeTai' => 'Cấp trường',
                'LoaiDeTai' => 'Ứng dụng',
                'ThoiGianBatDau' => '2024-02-01',
                'ThoiGianKetThuc' => '2025-02-01',
                'TrangThai' => 'đang thực hiện',
                'MucTieu' => 'IoT',
                'NoiDungChinh' => 'Cảm biến',
                'ThanhVien' => 'Dũng,Tuấn',
                'KetQua' => 'Đang test',
                'FileSanPham' => 'sp4.pdf',
                'KinhPhi' => 18000000,
            ],
            [
                'MaSo' => 5,
                'TenDeTai' => 'Deep Learning nhận dạng ảnh',
                'ChuNhiem' => 'Đặng Minh Tuấn',
                'DonVi' => 'AI',
                'CapDeTai' => 'Cấp bộ',
                'LoaiDeTai' => 'Nghiên cứu',
                'ThoiGianBatDau' => '2023-06-01',
                'ThoiGianKetThuc' => '2024-06-01',
                'TrangThai' => 'hoàn thành',
                'MucTieu' => 'DeepLearning',
                'NoiDungChinh' => 'CNN',
                'ThanhVien' => 'Tuấn,Hiếu',
                'KetQua' => 'Đã xong',
                'FileSanPham' => 'sp5.pdf',
                'KinhPhi' => 35000000,
            ],
            [
                'MaSo' => 6,
                'TenDeTai' => 'Data Mining',
                'ChuNhiem' => 'Nguyễn Hoàng Nam',
                'DonVi' => 'CNTT',
                'CapDeTai' => 'Cấp trường',
                'LoaiDeTai' => 'Nghiên cứu',
                'ThoiGianBatDau' => '2024-05-01',
                'ThoiGianKetThuc' => '2025-05-01',
                'TrangThai' => 'đang thực hiện',
                'MucTieu' => 'Khai phá dữ liệu',
                'NoiDungChinh' => 'Thuật toán',
                'ThanhVien' => 'Nam,Linh',
                'KetQua' => 'Đang làm',
                'FileSanPham' => 'sp6.pdf',
                'KinhPhi' => 22000000,
            ],
            [
                'MaSo' => 7,
                'TenDeTai' => 'Hệ thống chatbot',
                'ChuNhiem' => 'Trần Quốc Bảo',
                'DonVi' => 'AI',
                'CapDeTai' => 'Cấp trường',
                'LoaiDeTai' => 'Ứng dụng',
                'ThoiGianBatDau' => '2024-04-01',
                'ThoiGianKetThuc' => '2024-11-01',
                'TrangThai' => 'đang thực hiện',
                'MucTieu' => 'Chatbot',
                'NoiDungChinh' => 'NLP',
                'ThanhVien' => 'Bảo,Trang',
                'KetQua' => 'Đang dev',
                'FileSanPham' => 'sp7.pdf',
                'KinhPhi' => 17000000,
            ],
            [
                'MaSo' => 8,
                'TenDeTai' => 'Bảo mật hệ thống web',
                'ChuNhiem' => 'Phạm Thanh Long',
                'DonVi' => 'CNTT',
                'CapDeTai' => 'Cấp bộ',
                'LoaiDeTai' => 'Nghiên cứu',
                'ThoiGianBatDau' => '2023-03-01',
                'ThoiGianKetThuc' => '2024-03-01',
                'TrangThai' => 'hoàn thành',
                'MucTieu' => 'Security',
                'NoiDungChinh' => 'PenTest',
                'ThanhVien' => 'Long,Huy',
                'KetQua' => 'Hoàn thành',
                'FileSanPham' => 'sp8.pdf',
                'KinhPhi' => 26000000,
            ],
            [
                'MaSo' => 9,
                'TenDeTai' => 'Cloud Computing',
                'ChuNhiem' => 'Lý Văn Đức',
                'DonVi' => 'CNTT',
                'CapDeTai' => 'Cấp trường',
                'LoaiDeTai' => 'Nghiên cứu',
                'ThoiGianBatDau' => '2024-06-01',
                'ThoiGianKetThuc' => '2025-06-01',
                'TrangThai' => 'đang thực hiện',
                'MucTieu' => 'Cloud',
                'NoiDungChinh' => 'AWS',
                'ThanhVien' => 'Đức,Hoàng',
                'KetQua' => 'Đang làm',
                'FileSanPham' => 'sp9.pdf',
                'KinhPhi' => 21000000,
            ],
            [
                'MaSo' => 10,
                'TenDeTai' => 'Hệ thống quản lý học tập',
                'ChuNhiem' => 'Nguyễn Văn An',
                'DonVi' => 'CNTT',
                'CapDeTai' => 'Cấp trường',
                'LoaiDeTai' => 'Ứng dụng',
                'ThoiGianBatDau' => '2024-02-01',
                'ThoiGianKetThuc' => '2024-12-01',
                'TrangThai' => 'đang thực hiện',
                'MucTieu' => 'LMS',
                'NoiDungChinh' => 'Web System',
                'ThanhVien' => 'An,Trang',
                'KetQua' => 'Đang dev',
                'FileSanPham' => 'sp10.pdf',
                'KinhPhi' => 15000000,
            ],
        ]);
    }
}

